# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e231efed0413e49eb50cede914c2cdf17c85f8513442de30997e787bd920085807f54236dee1e8f78a5781c4196e6defebab1790c088fece0cc2dcc1bbe4cf03

test:
  secret_key_base: 305817e0fcb140da93381c3934e4b2f51e9c10927caf18313487641713b02a7a652c4e24aaed3f434bf738e3c821690357f1083272a76f0d338359c2b06b0dcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
